language: ruby
rvm:
  - 2.3.1
  - jruby
  - rbx
gemfile:
  - spec/gemfiles/rails_4_2.gemfile
  - spec/gemfiles/rails_5_0.gemfile
git:
  submodules: false
env:
  global:
  - COVERAGE=1
  - TRAVIS=1
  # codeclimate.com repo token:
  - secure: Kh43fq+MfpGNfQ/0IBhMnbzixVS5+K2QFPPwYfcS9ISgMASY2MAbNS1ZaD9HJ5Ynta8tnqS2QodwfQavDYI4tsFXcJ8RXbGK7GX2BKKuhH2ZfwuTGgltg0W1zTJR/18PL6jlMqon4lPnjaQQhis/WhBHqjkxHNIDzYWocZo/hc0=
matrix:
  allow_failures:
  - rvm: rbx
  exclude:
  - rvm: jruby
    gemfile: spec/gemfiles/rails_5_0.gemfile
sudo: false
cache: bundler
bundler_args: --path ../../vendor/bundle --without debug

script:
- bundle exec rspec --format d
- bundle exec codeclimate-test-reporter
